# Generated by Django 6.0.1 on 2026-02-22 12:00

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        # MessagingSettings
        migrations.CreateModel(
            name='MessagingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                # WhatsApp
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='WhatsApp Enabled')),
                ('whatsapp_api_token', models.CharField(blank=True, max_length=500, verbose_name='WhatsApp API Token')),
                ('whatsapp_phone_id', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp Phone ID')),
                ('whatsapp_business_id', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp Business ID')),
                # SMS
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS Enabled')),
                ('sms_provider', models.CharField(choices=[('none', 'None'), ('twilio', 'Twilio'), ('messagebird', 'MessageBird')], default='none', max_length=20, verbose_name='SMS Provider')),
                ('sms_api_key', models.CharField(blank=True, max_length=255, verbose_name='SMS API Key')),
                ('sms_sender_name', models.CharField(blank=True, max_length=11, verbose_name='SMS Sender Name')),
                # Email
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email Enabled')),
                ('email_from_name', models.CharField(blank=True, max_length=255, verbose_name='From Name')),
                ('email_from_address', models.EmailField(blank=True, max_length=254, verbose_name='From Email Address')),
                ('email_smtp_host', models.CharField(blank=True, max_length=255, verbose_name='SMTP Host')),
                ('email_smtp_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('email_smtp_username', models.CharField(blank=True, max_length=255, verbose_name='SMTP Username')),
                ('email_smtp_password', models.CharField(blank=True, max_length=255, verbose_name='SMTP Password')),
                ('email_smtp_use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                # Automation
                ('appointment_reminder_enabled', models.BooleanField(default=False, verbose_name='Appointment Reminders')),
                ('appointment_reminder_hours', models.IntegerField(default=24, verbose_name='Reminder Hours Before')),
                ('booking_confirmation_enabled', models.BooleanField(default=True, verbose_name='Booking Confirmations')),
            ],
            options={
                'db_table': 'messaging_settings',
                'verbose_name': 'Messaging Settings',
                'verbose_name_plural': 'Messaging Settings',
                'abstract': False,
                'unique_together': {('hub_id',)},
            },
        ),
        # MessageTemplate
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('all', 'All Channels')], default='all', max_length=20, verbose_name='Channel')),
                ('category', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('booking_confirmation', 'Booking Confirmation'), ('receipt', 'Receipt'), ('marketing', 'Marketing'), ('custom', 'Custom')], default='custom', max_length=30, verbose_name='Category')),
                ('subject', models.CharField(blank=True, help_text='Email subject line', max_length=255, verbose_name='Subject')),
                ('body', models.TextField(help_text='Message body with {{variables}}', verbose_name='Body')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_system', models.BooleanField(default=False, verbose_name='System Template')),
            ],
            options={
                'db_table': 'messaging_template',
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['category', 'name'],
                'abstract': False,
            },
        ),
        # Message
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], max_length=20, verbose_name='Channel')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Recipient Name')),
                ('recipient_contact', models.CharField(help_text='Phone number or email address', max_length=255, verbose_name='Recipient Contact')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='queued', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('external_id', models.CharField(blank=True, help_text='Provider message ID', max_length=255, verbose_name='External ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.messagetemplate', verbose_name='Template')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'db_table': 'messaging_message',
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [
                    models.Index(fields=['hub_id', 'channel', 'status', '-created_at'], name='messaging_m_hub_id_chan_idx'),
                ],
            },
        ),
        # Campaign
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Campaign Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('all', 'All Channels')], max_length=20, verbose_name='Channel')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='Total Recipients')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Sent Count')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='Delivered Count')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Failed Count')),
                ('target_filter', models.JSONField(blank=True, default=dict, help_text='Customer filter criteria', verbose_name='Target Filter')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='messaging.messagetemplate', verbose_name='Template')),
            ],
            options={
                'db_table': 'messaging_campaign',
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
