# Generated by Django 6.0.1 on 2026-02-23 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerfield_customertag_customer_anniversary_and_more'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='Status')),
                ('trigger_data', models.JSONField(blank=True, default=dict, verbose_name='Trigger Data')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled For')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Executed At')),
            ],
            options={
                'verbose_name': 'Automation Execution',
                'verbose_name_plural': 'Automation Executions',
                'db_table': 'messaging_automation_execution',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageAutomation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Automation Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('trigger', models.CharField(choices=[('welcome', 'New Customer Welcome'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('post_sale', 'After Sale'), ('post_appointment', 'After Appointment'), ('inactivity', 'Customer Inactivity'), ('loyalty_tier_change', 'Loyalty Tier Change'), ('lead_stage_change', 'Lead Stage Change'), ('ticket_resolved', 'Ticket Resolved'), ('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('custom', 'Custom Trigger')], max_length=30, verbose_name='Trigger')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('all', 'All Channels')], default='email', max_length=20, verbose_name='Channel')),
                ('delay_hours', models.IntegerField(default=0, help_text='Hours to wait after trigger before sending', verbose_name='Delay (hours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Additional conditions (e.g., inactivity_days: 30)', verbose_name='Conditions')),
                ('total_sent', models.PositiveIntegerField(default=0, verbose_name='Total Sent')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Triggered')),
            ],
            options={
                'verbose_name': 'Message Automation',
                'verbose_name_plural': 'Message Automations',
                'db_table': 'messaging_automation',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_hub_id_8428bc_idx',
            old_name='messaging_m_hub_id_chan_idx',
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_executions', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_executions', to='messaging.message', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messageautomation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to='messaging.messagetemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='messaging.messageautomation', verbose_name='Automation'),
        ),
    ]
